### PR TITLE
Use a directive based on umb-tabbed-content

### PR DESCRIPTION
**Pull request by erikjanwestendorp**
Refactored / Replaced some code to make it less hacky (IMHO). It also solved the issue with split view. Feel free to give some feedback :) https://github.com/nul800sebastiaan/Cultiv.Tabify/issues/4

image

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Thanks @erikjanwestendorp ! That really looks much better already.

Unfortunately, it only works on the home page for some reason.. any other page doesn't want to show the initial tab until clicking on it. Any chance you can look into that please?

pr6

**Comment by nul800sebastiaan** [comment]
Ah, probably because the Hero tab is hardcoded! :-)

https://github.com/nul800sebastiaan/Cultiv.Tabify/pull/6/files#diff-1d17c01cb62917783f96601c5f3148acR9

**Comment by erikjanwestendorp** [comment]
@nul800sebastiaan Oops... I solved it in my last commit :)

https://github.com/nul800sebastiaan/Cultiv.Tabify/pull/6/commits/24d5817114da73b7a90549dee17f31aa23dc35e3

**Comment by nul800sebastiaan** [comment]
Nice one! Thanks very much, great with the split view working too, fixes #4

**Pull request merged**
